### ISSUE TITLE
Cannot get last media query to work

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/responsive-image-section#1]
Hi Thomas,
Can you help me with my last media query, I don't know how to make it smaller to match with markbot.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Looks like you’re missing a `max-width`—something to contain the content. On an element inside the grey box, that surrounds everything.

**Comment by fuen0015** [comment]
It worked for 60em but now 90em media query is not right, do a need to add max width again?

**Comment by thomasjbradley** [comment]
It’s something else. You need to center that `max-width` thing on the page.

**Comment by fuen0015** [comment]
Unfortunately I don't understand

**Comment by thomasjbradley** [comment]
https://learn-the-web.algonquindesign.ca/topics/css-layout-cheat-sheet/#centering-elements

**Comment by fuen0015** [comment]
Got it, thank you :D
